-- Run this in the Supabase SQL editor. Idempotent — safe to rerun.
--
-- Access model:
--   - All access happens from Vercel serverless functions (/api/*)
--     using the service-role key, which bypasses RLS
--   - RLS is enabled with NO policies, so anon/authenticated roles
--     (i.e. the browser if the anon key ever leaked) have zero access
--   - UPDATE, DELETE, TRUNCATE are revoked from every non-owner role,
--     so even a leaked service-role key cannot modify or remove rows.
--     The only way to edit is a direct DB session as the table owner.

create table if not exists public.leaderboard (
  id          bigint generated by default as identity primary key,
  initials    text not null check (char_length(initials) between 1 and 3),
  score       integer not null check (score >= 0),
  rank        text,
  created_at  timestamptz not null default now()
);

create index if not exists leaderboard_score_desc_idx
  on public.leaderboard (score desc);

alter table public.leaderboard enable row level security;

-- Clean up anything from earlier iterations of this file.
drop policy   if exists "leaderboard read"  on public.leaderboard;
drop policy   if exists "leaderboard write" on public.leaderboard;
drop function if exists public.submit_score(text, integer, text);

-- Lock down modifications at the privilege layer (defense-in-depth).
-- Rows become append-only for every role that reaches the table through
-- the REST API, including service_role.
revoke update, delete, truncate on public.leaderboard
  from public, anon, authenticated, service_role;
