-- Run this in the Supabase SQL editor. Idempotent — safe to rerun.
--
-- Access model:
--   - All access happens from Vercel serverless functions (/api/*)
--     using the service-role key, which bypasses RLS
--   - RLS is enabled with NO policies, so the anon/authenticated roles
--     (i.e. the browser if the anon key ever leaked) have zero access

create table if not exists public.leaderboard (
  id          bigint generated by default as identity primary key,
  initials    text not null check (char_length(initials) between 1 and 3),
  score       integer not null check (score >= 0),
  rank        text,
  created_at  timestamptz not null default now()
);

create index if not exists leaderboard_score_desc_idx
  on public.leaderboard (score desc);

alter table public.leaderboard enable row level security;

-- Clean up anything from earlier iterations of this file.
drop policy   if exists "leaderboard read"  on public.leaderboard;
drop policy   if exists "leaderboard write" on public.leaderboard;
drop function if exists public.submit_score(text, integer, text);
