/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cat.glb --transform --types 
Files: public/cat.glb [2.87MB] > /Users/mattgreenberg/dev/demos/skate-cat/cat-transformed.glb [406.41KB] (86%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    wall: THREE.Mesh
    defaultMaterial006: THREE.Mesh
    defaultMaterial: THREE.Mesh
    defaultMaterial003: THREE.Mesh
    Object_6: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    dingus_dingus_0: THREE.Mesh
    dingus_whiskers_0: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    TVfront: THREE.MeshStandardMaterial
    TVback: THREE.MeshStandardMaterial
    TVScreen: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    dingus: THREE.MeshStandardMaterial
    whiskers: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cat-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.wall.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.TVfront} position={[0.27, 0.027, 0.039]} rotation={[-Math.PI, -0.715, -Math.PI]} scale={0.029} />
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.TVback} position={[0.381, 0.777, 0.649]} rotation={[0, 0.715, 0]} scale={[0.028, 0.028, 0.029]} />
      <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.TVScreen} position={[-2.74, 0.778, -2.948]} rotation={[0, 0.715, 0]} scale={11.381} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[0, 0, 2.985]} rotation={[-3.074, 0.289, 3.063]} scale={[0.934, 0.99, 0.99]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} position={[-0.001, 0.017, 2.986]} rotation={[-3.074, 0.289, 3.063]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[-0.193, 0.644, 3.472]} rotation={[1.934, 0.177, -2.994]} scale={[0.4, 0.294, 0.354]} />
      <mesh geometry={nodes.dingus_dingus_0.geometry} material={materials.dingus} position={[1.36, 0, 2.18]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03} />
      <mesh geometry={nodes.dingus_whiskers_0.geometry} material={materials.whiskers} position={[1.36, 0, 2.18]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/cat-transformed.glb')
