/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/intro/vintage_tv.glb --transform --types 
Files: public/intro/vintage_tv.glb [3.05MB] > /Users/mattgreenberg/dev/demos/skate-cat/vintage_tv-transformed.glb [233.92KB] (92%)
Author: Outlier Spa (https://sketchfab.com/outlier_spa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-tv-54b56ce71d054d60ab31425757a45cf7
Title: Vintage TV
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tv-b_low_tv-retro_0']: THREE.Mesh
  }
  materials: {
    ['tv-retro']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/vintage_tv-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tv-b_low_tv-retro_0'].geometry} material={materials['tv-retro']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/vintage_tv-transformed.glb')
